DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS STATS;
DROP TABLE IF EXISTS MESSAGE;

CREATE TABLE USER (
	userId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name TEXT,
	age INTEGER,
	sex TEXT,
	email TEXT,
	password TEXT,
	city TEXT
);

CREATE TABLE STATS (
	userId INTEGER PRIMARY KEY,
	bench REAL,
	deadlift REAL,
	squat REAL,
	FOREIGN KEY (userId) REFERENCES USER(userId)
);

CREATE TABLE MESSAGE (
	messageId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	senderId INTEGER NOT NULL,
	receiverId INTEGER NOT NULL,
	message TEXT,
	time INTEGER,
	status TEXT,
	FOREIGN KEY (senderId) REFERENCES USER(userId),
	FOREIGN KEY (receiverId) REFERENCES USER(userId)
);