DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS STATS;
DROP TABLE IF EXISTS MESSAGE;

CREATE TABLE USER (
	userId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	firstName TEXT,
	lastName TEXT,
	dateOfBirth TEXT,
	email TEXT,
	password TEXT
);

CREATE TABLE STATS (
	userId INTEGER PRIMARY KEY,
	city TEXT,
	bench REAL,
	deadlift REAL,
	squat REAL,
	FOREIGN KEY (userId) REFERENCES USER(userId)
);

CREATE TABLE MESSAGE (
	usr1 INTEGER NOT NULL,
	usr2 INTEGER NOT NULL,
	message TEXT,
	time INTEGER,
	status TEXT,
	PRIMARY KEY (usr1, usr2)
);